### ISSUE TITLE
想请问一下为什么我的使用jetson orin运行这个ros包时，并没有出现目标检测

### ISSUE THREAD

**Issue by EzioPeter** [qq44642754a/Yolov8_ros#7]
我最开始时直接pip安装的pytorch官网的torch版本，这个是可以实现目标检测的，但是帧率只有1帧，我发现这是因为我torch.cuda.is_available()为false，所以使用了cpu来计算。后来将pytorch版本改为了nvidia官方提供的pytorch版本，这样运行帧率提高了，因为挂载到了cuda上，但是显示的图像并没有运行目标检测，这是因为什么呢

**Comment by liu-lu-eng** [comment]
请问你的问题解决了么，我也遇到了同样的问题，只有实时画面，但是没有检测框，请问你是如何解决的呀？

**Comment by qq44642754a** [comment]
这个我不太清楚，我试过nano和agx都没有出现这个问题

**Comment by liu-lu-eng** [comment]
好的，非常感谢你的回复，我再查查其他资料

---- 回复的原邮件 ----
| 发件人 | Zhitao ***@***.***> |
| 发送日期 | 2024年06月19日 09:51 |
| 收件人 | qq44642754a/Yolov8_ros ***@***.***> |
| 抄送人 | liu-lu-eng ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [qq44642754a/Yolov8_ros] 想请问一下为什么我的使用jetson orin运行这个ros包时，并没有出现目标检测 (Issue #7) |

这个我不太清楚，我试过nano和agx都没有出现这个问题

**Comment by XJX-Cau** [comment]
注意yolo_v8.py中这个代码修改如何self.model = YOLO(weight_path).to("cuda:0")。
 计算过程采用GPU才行. 我试过了，没问题了

**Comment by liu-lu-eng** [comment]
好的，非常谢谢你🙏

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年12月03日 09:10 |
| 收件人 | qq44642754a/Yolov8_ros ***@***.***> |
| 抄送人 | liu-lu-eng ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [qq44642754a/Yolov8_ros] 想请问一下为什么我的使用jetson orin运行这个ros包时，并没有出现目标检测 (Issue #7) |

注意yolo_v8.py中这个代码修改如何self.model = YOLO(weight_path).to("cuda:0")。
计算过程采用GPU才行. 我试过了，没问题了
